### ISSUE TITLE
ImportError pyserial cannot import name 'portNotOpenError' from 'serial.serialutil'

### ISSUE THREAD

**Issue by dlwalter** [ampledata/dummyserial#4]
```
>>> import dummyserial
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/dummyserial/__init__.py", line 17, in <module>
    from .classes import Serial  # NOQA
  File "/usr/local/lib/python3.9/site-packages/dummyserial/classes.py", line 11, in <module>
    from serial.serialutil import SerialException, portNotOpenError
ImportError: cannot import name 'portNotOpenError' from 'serial.serialutil' (/usr/local/lib/python3.9/site-packages/serial/serialutil.py)

```

Looks like this is fixed by a PR awaiting approval

**Comment by chrisdel101** [comment]
I'm having the same problem. I see the package hasn't been touched in 6 years. Too bad it doesn't work.
